/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#1E1E1E',
        'surface-dim': '#131313',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-raised': '#2A2A2A',
        'border-subtle': '#333333',
        primary: '#adc6ff',
        'primary-container': '#4d8eff',
        'on-primary': '#002e6a',
        'on-primary-container': '#00285d',
        secondary: '#4edea3',
        'secondary-container': '#00a572',
        'on-secondary': '#003824',
        'on-secondary-container': '#00311f',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A0A0A0',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        error: '#ffb4ab',
        'error-container': '#93000a',
        tertiary: '#c0c1ff',
        'tertiary-container': '#8083ff',
        'on-tertiary-container': '#0d0096',
      },
      spacing: {
        'margin-edge': '32px',
        'container-max': '1280px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
    },
  },
  plugins: [],
};
